# fly.toml app configuration file generated for singapore-way-chatbot on 2025-05-25T06:31:19+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'singapore-way-chatbot'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
